### ISSUE TITLE
OSX 10.10 support

### ISSUE THREAD

**Issue by endelwar** [kmikiy/SpotMenu#1]
Is it possible to get OSX 10.10 support for version 1.2?

**Comment by kmikiy** [comment]
The minimum requirement of 10.11 was introduced because I use Alamofire/AlamofireImage to download the album artwork based on the url information (unfortunetly there is no official way to retrieve the artwork image from spotify directly). The minimum requirement for Alamofire/AlamofireImage 3.0 is 10.11.
After upgrading to Xcode 8 and swift 3.0 the version of Alamofire I use was also upgraded.
I will try to omit the use of Alamofire to support 10.10 again.

**Comment by kmikiy** [comment]
@endelwar I have completely deintegrated cocoapods from the project. Removed all Alamofire dependencies. Version 1.2 should now work with 10.10. Please give it a try and let me know :)

**Comment by endelwar** [comment]
I don't see any changes in git repository, apart from a README edit, and SpotMenu_1_2.zip is 27 days old. Did you updated github repository?

**Comment by kmikiy** [comment]
@endelwar you were right, I forgot to push the changes. Check again :)

**Comment by endelwar** [comment]
It works like a charm! Thanks!
