### ISSUE TITLE
Small issue: Menu bar icon flickering when using with Bartender 2

### ISSUE THREAD

**Issue by fabi94music** [kmikiy/SpotMenu#32]
I'm using Bartender 2 and the app icon seems to flicker, when Spotify is closed and only the icon is shown in the menu bar. 

See:
https://giphy.com/gifs/TFyEvilXxi4iQ

**Comment by kmikiy** [comment]
hmm, I think I know why that happens. I'll see what i can do to fix it.

**Comment by fabi94music** [comment]
Cool! :) Have you read my latest command on the other issue 😆 ?
Haha seriously, recommended your app every fellow student I met at university using Spotify on Mac :P

Btw, noticed a little high CPU usage though 🙈 
![ohne titel](https://user-images.githubusercontent.com/29753374/28264339-caa5c2de-6aea-11e7-8044-032091efe3e8.jpg)

**Comment by kmikiy** [comment]
If you check the option to always show the app icon does it still flicker?

**Comment by fabi94music** [comment]
When the option Show SpotMenu Icon is checked, there is no flickering :)

**Comment by kmikiy** [comment]
Yeah, so the flickering occurs because if you uncheck the option to show icons. Then when music isn't playing in Spotify, nothing would be shown on the status bar, therefore you wouldn't be able to close the app, or open the popover. That's why I add the icon back, you see the flickering because the app checks Spotify for any info, removes the icon because that is what is set, then sees that there is no music playing so it re-adds the icon which is not noticeable in the status bar but can be noticed in the bartender app.
I hope that this is good for a quickfix for you, but I'll check later to see if I can implement it somehow without flickering no matter what you have set in the preferences.

Maybe this caused the energy issue?
SpotMenu never really goes above these values for me.

<img width="913" alt="screen shot 2017-07-17 at 15 21 24" src="https://user-images.githubusercontent.com/14206503/28269838-b85cb632-6b03-11e7-8a3c-05ee92ab8370.png">
<img width="655" alt="screen shot 2017-07-17 at 15 20 51" src="https://user-images.githubusercontent.com/14206503/28269839-b8636446-6b03-11e7-80c3-7f67d0236a30.png">

By the way skipping through a lot of songs at once may cause high cpu usage because the album artwork is downloaded from the internet, because only the url of the artwork can be retrieved from Spotify through its Apple Script API

**Comment by fabi94music** [comment]
Ah thank you, that makes sense :) And downloading the artwork explains, why no artwork is shown on offline mode. 
Could you also provide the option to show the mini player like in this screenshot? => 

![bildschirmfoto 2017-07-17 15 55 03_99zyh8](https://user-images.githubusercontent.com/29753374/28271375-a09deaac-6b08-11e7-853e-b72552b8c132.jpg)

**Comment by kmikiy** [comment]
@fabi94music Same goes for here. I am closing the issue because the flickering has been addressed. 
Please open a new issue for each of the requests 🙂

**Comment by fabi94music** [comment]
You said, you will check if you could implement it somehow without flickering no matter what I have set in the preferences. Could you solve it?

**Comment by kmikiy** [comment]
Fixed in version 1.5.1
