### ISSUE TITLE
Can you add an option to hide the spotify and 'playing' icon in the menu bar? I prefer having just the name of the song and the artist.

### ISSUE THREAD

**Issue by mchang168** [kmikiy/SpotMenu#4]

**Comment by kmikiy** [comment]
Hi, I added a new version: [v1.2.1](https://github.com/kmikiy/SpotMenu/raw/master/SpotMenu_1_2_1.zip).
This will only show the icon when spotify isn't open and no music is playing (otherwise you would only be able to close this app from the activity monitor, or by starting spotify first). If you don't want the icon to be visible at all, then let me know and i'll remove it.
Furthermore, making this configurable through the application would take more time for me, this was just a quick fix. I might take the time and do it properly later on.

**Comment by mchang168** [comment]
Hi, 

This is perfect. Thank you very much
