### ISSUE TITLE
Dependency issue trying to run in XCode

### ISSUE THREAD

**Issue by csherm08** [kmikiy/SpotMenu#54]
None of your accounts are a member of '3K79XCJYWL':  An unexpected error occurred. Xcode cannot find a team matching '3K79XCJYWL'.
No signing certificate "Mac Development" found:  No "Mac Development" signing certificate matching team ID "3K79XCJYWL" with a private key was found.

**Comment by kmikiy** [comment]
<img width="783" alt="screen shot 2017-08-21 at pm 5 39 03" src="https://user-images.githubusercontent.com/14206503/29527070-e87c654c-8697-11e7-8534-fb784c9e5963.png">

Hey, try changing the bundle identifier to something unique and also change the team to your own personal team.
SpotMenuToday (today widget) needs to be signed in order to work.
