### ISSUE TITLE
Preferences

### ISSUE THREAD

**Issue by lumberjack76** [kmikiy/SpotMenu#79]
I am unable t open the preferences. ive tried right clicking and control + right click but nothing happens.

**Comment by kmikiy** [comment]
hi, which version of SpotMenu are you using?
Could you please try a previous version and see if it works (e.g [1.6](https://github.com/kmikiy/SpotMenu/releases/tag/v1.6))
[All releases](https://github.com/kmikiy/SpotMenu/releases)

**Comment by lumberjack76** [comment]
I originally tried it on 1.7. I just downloaded 1.6 and im experiencing the same issue unfortunately.

**Comment by xylein** [comment]
@kmikiy @lumberjack76 I am facing a similar issue. I am on 1.7 (I downloaded the latest today) and Sierra 10.12.5. Everytime I click on Preferences, the application closes. Right clicking on the bar and then doing Command+, (as opposed to clicking) achieves the same output.

**Comment by jincastillo992** [comment]
im having the exact same issue. dont know for how long, just saw this happening today

**Comment by kmikiy** [comment]
Could one of you follow the steps from [how to build](https://github.com/kmikiy/SpotMenu#how-to-build) and show me what it writes to the console and where the app stops in the code when the app crashes?

**Comment by IcemanYVR** [comment]
I am having a similar issue in 1.7 (and all other installed versions) where Control clicking the Spotify Icon in the Menu Bar or pressing "CMD+," does not open preferences. No crashes, freezing, or app closing, just nothing happens.
OS X 10.12.6, Spotify 1.0.69.336.g7edcc575
I have deleted 1.7 from the computer and installed 1.6. The same issue still occurs.

**Comment by hugopenaranda** [comment]
I had the same issue. Usually I leave the right click on magic mouse disabled. So, I couldn't access "preferences" using control+click. I had to enable right click in Mac OS System Preferences and them it worked, I right-clicked the app at the menu bar and could see the preferences menu.

**Comment by jdickey** [comment]
I run into this problem with SpotMenu 1.8 on OS X 10.11.6.

Enabling the Magic Mouse right-click in System Preferences allows the menu to be displayed. The bug is that control-click should have the same effect (according to the [Apple Human Interface Guidelines](https://developer.apple.com/macos/human-interface-guidelines/user-interaction/mouse-and-trackpad/) and [*How to right-click on Mac*](https://support.apple.com/en-sg/HT207700) in Apple Support).

This Mac is sometimes used by people who've been trained that "to right-click on Mac, use control-click"; it therefore doesn't matter *where* on the mouse they tap or scroll. I'd like to reduce potential confusion by keeping the *Secondary click* box in the Mouse preferences cleared.

**Comment by kmikiy** [comment]
Thanks for the feedback everyone. I have fixed this in commit https://github.com/kmikiy/SpotMenu/commit/dfd43bf4f8f00f31d3a7998f06046dc06e04e567. It will be available in the next release. Until then, please use the two finger right click method or the right button on your mouses.
